create table evento (id bigint not null, data varchar(255), horario varchar(255), local varchar(255), nome varchar(255), primary key (id)) type=MyISAM;
create table hibernate_sequence (next_val bigint) type=MyISAM;
insert into hibernate_sequence values ( 1 );
create table evento (id bigint not null, data varchar(255), horario varchar(255), local varchar(255), nome varchar(255), primary key (id)) type=MyISAM;
create table hibernate_sequence (next_val bigint) type=MyISAM;
insert into hibernate_sequence values ( 1 );
create table evento (id bigint not null, data varchar(255), horario varchar(255), local varchar(255), nome varchar(255), primary key (id)) type=MyISAM;
create table hibernate_sequence (next_val bigint) type=MyISAM;
insert into hibernate_sequence values ( 1 );
create table evento (id bigint not null, data varchar(255), horario varchar(255), local varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table evento (id bigint not null, data varchar(255), horario varchar(255), local varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
